version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/cicdapp
permissions:
  - object: /home/ubuntu/cicdapp/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
#  ApplicationStart:
#    - location: scripts/start.sh
#      timeout: 60
#      runas: ubuntu